version: "3.9"

volumes:
  shared-workspace:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '../src'

networks:
  kafka-spark-network:
    name: kafka-spark-network
    external: true

services:
  spark-master:
    image: spark-master
    container_name: spark-master
    hostname: spark-master
    ports:
      - 9090:9090
      - 7077:7077
    volumes:
      - shared-workspace:/opt/workspace
    networks:
      - kafka-spark-network
    environment:
      - SPARK_LOCAL_IP=spark-master
      - GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS}
      - SPARK_MASTER_WEBUI_PORT=9090
  spark-worker-1:
    image: spark-worker
    container_name: spark-worker-1
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=1G
      - SPARK_DRIVER_MEMORY=1G
      - SPARK_EXECUTOR_MEMORY=1G
      - SPARK_WORKLOAD=worker
      - SPARK_LOCAL_IP=spark-worker-1
      - GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS}
    ports:
      - 8083:8081
    networks:
      - kafka-spark-network
    volumes:
      - shared-workspace:/opt/workspace
    depends_on:
      - spark-master
  spark-worker-2:
    image: spark-worker
    container_name: spark-worker-2
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=1G
      - SPARK_DRIVER_MEMORY=1G
      - SPARK_EXECUTOR_MEMORY=1G
      - SPARK_WORKLOAD=worker
      - SPARK_LOCAL_IP=spark-worker-2
      - GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS}
    ports:
      - 8082:8081
    networks:
      - kafka-spark-network
    volumes:
      - shared-workspace:/opt/workspace
    depends_on:
      - spark-master
